[package]
name = "easychangedirectory"
description = "Tools for easy cd"
version = "0.5.2"
authors = ["dijdzv <dijdzv@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dijdzv/easychangedirectory"
edition = "2021"
categories = ["command-line-utilities", "filesystem"]
keywords = ["cli","terminal","cd"]

[dependencies]
anyhow = "1.0.60"
clap = { version = "3.2.16", features = ["cargo"] }
crossterm = "0.24.0"
envy = "0.4.2"
handlebars = "4.3.3"
home = "0.5.4"
log = "0.4.17"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.83"
simplelog = "0.12.1"
tui = "0.18.0"

[profile.release]
lto = true
codegen-units = 1