[package]
name = "easychangedirectory"
version = "0.1.0"
authors = ["@shsyss"]
edition = "2021"
description = "cli tool to comfortably change directories"
# build = "build.rs"

[dependencies]
anyhow = "1.0.60"
clap = { version = "3.2.16", features = ["cargo"] }
crossterm = "0.24.0"
serde = { version = "1.0.142", features = ["derive"] }
tinytemplate = "1.2.1"
tui = "0.18.0"

# [build-dependencies]
# clap = { version = "3.2.16", features = ["cargo"] }
# clap_complete = "3.2.3"

[profile.release]
lto = true
codegen-units = 1
