[package]
name = "easychangedirectory"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "./src/main.rs"
name = "ecd"

[dependencies]
crossterm = "0.24.0"
tui = "0.18.0"

[profile.release]
lto = true