[package]
name = "easychangedirectory"
version = "0.1.0"
authors = ["shsyss <shibata.syungo@gmail.com>"]
edition = "2021"
description = "Tools for easy cd"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/shsyss/easychangedirectory"
categories = ["command-line-utilities", "filesystem"]
keywords = ["cli","terminal","cd"]

[dependencies]
anyhow = "1.0.60"
clap = { version = "3.2.16", features = ["cargo"] }
crossterm = "0.24.0"
handlebars = "4.3.3"
serde_json = "1.0.83"
tui = "0.18.0"

[profile.release]
lto = true
codegen-units = 1
