[package]
name = "easychangedirectory"
version = "0.1.0"
authors = ["@shsyss"]
edition = "2021"
description = "cli tool to comfortably change directories"

[[bin]]
path = "./src/main.rs"
name = "ecd"

[dependencies]
anyhow = "1.0.59"
clap = { version = "3.2.16", features = ["cargo"] }
crossterm = "0.24.0"
tui = "0.18.0"

[profile.release]
lto = true
