# coverage:
#   status:
#     project:
#       default:
#         target: 100%
#         threshold: 90%
coverage:
  status:
    project:
      default:
        enabled: false
    patch:
      default:
        enabled: false
