max_width = 120
newline_style = "Native"
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

# imports_granularity = "Crate"
# format_code_in_doc_comments = true
# imports_indent = "Visual"
# group_imports = "StdExternalCrate"
# version = "Two"
# wrap_comments = true